version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'nisiter'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    container_name: mysql-db
    ports:
      - 3307:3306
    volumes:
      - ./docker-volume/mysql-volume:/var/lib/mysql

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: 'nisiter'
      MONGO_INITDB_ROOT_USERNAME: 'user'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    container_name: mongo-db
    ports:
      - 27017:27017
    volumes:
      - ./docker-volume/mongo-volume:/var/lib/mongodb
